name = "frelancer-turkiye"
compatibility_date = "2024-04-27"
pages_build_output_dir = ".vercel/output" # Common for next-on-pages

[[d1_databases]]
binding = "frelancer_db"
database_name = "frelancer_db"
database_id = "2b9ab9d6-644e-4682-a529-b9cbfa729d75" # To be filled by user
migrations_dir = "db"
